* 2016
** 2016-03 March
*** 2016-03-16 Wednesday
**** 股市真规则
***** 指标
****** 公司成长性
****** 公司盈利能力
******* 资产收益率
资产收益率（ROA）= 销售净利率 × 资产周转率

                   销售净利率 = 净利润 / 销售收入

                                 资产周转率 = 销售收入 / 资产


净资产收益率（ROE）= 资产收益率（ROA）× 财务杠杆比率
                   = 销售净利率 × 资产周转率 × 财务杠杆比率

                                                 财务杠杆比率 = 资产 / 所有者权益

一般来说，非金融类的公司在没有过多使用财务杠杆比率的前提下，能产生10%以上的净资产收益率，就是值得投资的。

注意：
金融类的公司财务杠杆普遍较高，需要对应较高的净资产收益率，如12%以上。
要当心过高的净资产收益率，因为那可能不真实，要仔细考察。
******* 自由现金流
自由现金流 = 经营性现金流 - 资本性支出

对于任何公司，%5以上的销售收入转化为自由现金流是必要的，这表明公司在产生超额现金方面做得不错。
******* 盈利能力矩阵
把净资产收益率和自由现金流放在一起考虑

高 |             |
   |             | 低风险公司
   |             |
自 |             |
由 |—————————————
现 |             |
金 |             |
流 |高风险公司   |
   |             |
   |             |
低 |_____________|_____________
     低     净资产收益率     高
******* 投入资本收益率（ROIC）慎用！
投入资本收益率（ROIC）= 税前净营业利润 / 投资资本
                                         投资资本 = 总资产 - 不附带利息的流动负债 - 自由现金流 - 商誉
****** 公司财务健康状况
******* 财务杠杆比率
财务杠杆比率 = 资产 / 所有者权益
******* 权益负债率（Debt to Equity）
权益负债率 = 长期负债 / 所有者权益
******* 已获利息倍数
已获利息倍数 = 息税前利润（EBIT）/ 利息费用
               息税前利润（EBIT）= 税前利润 +　利息费用

已获利息倍数越高越好，但很难确定低于什么值就不能接受。
******* 流动比率和速动比率
流动比率 = 流动资产 / 流动负债
一般惯例流动比率应在1.5左右或更高一些

速动比率 = （流动资产 - 存货）/ 流动负债
该比率对制造业和零售业特别有用，因为通常存货占用了大量现金。公司速动比率大于1.0可视为处于比较好的状态。
****** 空头情形
***** 危险信号
****** 衰退中的现金流
****** 连续的非经常性费用
****** 连续的收购
****** 首席财务官或审计师离开公司
****** 过快增长的应收账款
****** 变更赊销付款条件和应收账款
***** 估值
****** 市销率（P/S）
市销率（P/S）= 股票价格 / 每股销售收入
****** 市净率（P/B）
市净率（P/B）= 股票价格 / 每股净资产
****** 市盈率（P/E）
市盈率（P/E）= 股票价格 / 每股盈利

通常对越稳定的公司越有用，对前景越明朗的公司越有用。
具有较低成长性的公司应该有一个较低的市盈率
具有较高风险的公司应该有一个较低的市盈率
具有较高资本需求的公司应该有一个较低的市盈率

在使用市盈率时要思考如下问题：
公司最近出售业务或资产了吗
公司最近发生了一大笔非经常性费用吗
公司更有周期性吗
公司把把产生现金流的资产资本化还是费用化
盈利是真实的还是想象的
****** 市盈率相对盈利成长（PEG）
市盈率相对盈利成长（PEG）= 市盈率（P/E）/ 年盈利增长率
****** 股票的价值
股票的价值等于未来现金流总和的折现值（ CFn / ( 1 + R ) ^ n ）
****** 折现率
没有办法精确计算准确的折现率。需要记住的是：
当利率上升时，折现率也要上升
当公司风险水平提高时，折现率也要上升
******* 影响公司风险水平的因素
公司规模：规模越大风险越小
财务杠杆：负债越多风险越大。资产负债率，利息偿付比率
周期性：周期性行业的现金流比稳定性行业的现金流更难预测，风险更大
公司经营和管理：
竞争优势：
复杂性：公司越难理解风险越高

在晨星，用10.5%作为一般水平公司的折现率
****** 永续年金价值
**** 邓普顿教你逆向投资
1979年道琼斯工业指数股的平均市盈率为6.8，这是有史以来的最低水平，
根据价值线公司的研究，道琼斯工业指数股的长期平均市盈率为14.2
